[project]
name = "sex"
version = "0.1.0"
description = "My local Python package"
authors = [
    { name = "Othame", email = "chenzhu_912@zju.edu.cn" }
]
readme = ""
requires-python = ">=3.8"

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
