default.conv:  |
    CONV NORM
    # 3x3 ``all-ground'' convolution mask with FWHM = 2 pixels.
    1 2 1
    2 4 2
    1 2 1

gauss_3.0_7x7.conv: |
    CONV NORM
    # 7x7 convolution mask of a gaussian PSF with FWHM = 3.0 pixels.
    0.004963 0.021388 0.051328 0.068707 0.051328 0.021388 0.004963
    0.021388 0.092163 0.221178 0.296069 0.221178 0.092163 0.021388
    0.051328 0.221178 0.530797 0.710525 0.530797 0.221178 0.051328
    0.068707 0.296069 0.710525 0.951108 0.710525 0.296069 0.068707
    0.051328 0.221178 0.530797 0.710525 0.530797 0.221178 0.051328
    0.021388 0.092163 0.221178 0.296069 0.221178 0.092163 0.021388
    0.004963 0.021388 0.051328 0.068707 0.051328 0.021388 0.004963

default.nnw: | 
    NNW
    # Neural Network Weights for the SExtractor star/galaxy classifier (V1.3)
    # inputs:	9 for profile parameters + 1 for seeing.
    # outputs:	``Stellarity index'' (0.0 to 1.0)
    # Seeing FWHM range: from 0.025 to 5.5'' (images must have 1.5 < FWHM < 5 pixels)
    # Optimized for Moffat profiles with 2<= beta <= 4.

    3 10 10  1

    -1.56604e+00 -2.48265e+00 -1.44564e+00 -1.24675e+00 -9.44913e-01 -5.22453e-01  4.61342e-02  8.31957e-01  2.15505e+00  2.64769e-01
    3.03477e+00  2.69561e+00  3.16188e+00  3.34497e+00  3.51885e+00  3.65570e+00  3.74856e+00  3.84541e+00  4.22811e+00  3.27734e+00

    -3.22480e-01 -2.12804e+00  6.50750e-01 -1.11242e+00 -1.40683e+00 -1.55944e+00 -1.84558e+00 -1.18946e-01  5.52395e-01 -4.36564e-01 -5.30052e+00
    4.62594e-01 -3.29127e+00  1.10950e+00 -6.01857e-01  1.29492e-01  1.42290e+00  2.90741e+00  2.44058e+00 -9.19118e-01  8.42851e-01 -4.69824e+00
    -2.57424e+00  8.96469e-01  8.34775e-01  2.18845e+00  2.46526e+00  8.60878e-02 -6.88080e-01 -1.33623e-02  9.30403e-02  1.64942e+00 -1.01231e+00
    4.81041e+00  1.53747e+00 -1.12216e+00 -3.16008e+00 -1.67404e+00 -1.75767e+00 -1.29310e+00  5.59549e-01  8.08468e-01 -1.01592e-02 -7.54052e+00
    1.01933e+01 -2.09484e+01 -1.07426e+00  9.87912e-01  6.05210e-01 -6.04535e-02 -5.87826e-01 -7.94117e-01 -4.89190e-01 -8.12710e-02 -2.07067e+01
    -5.31793e+00  7.94240e+00 -4.64165e+00 -4.37436e+00 -1.55417e+00  7.54368e-01  1.09608e+00  1.45967e+00  1.62946e+00 -1.01301e+00  1.13514e-01
    2.20336e-01  1.70056e+00 -5.20105e-01 -4.28330e-01  1.57258e-03 -3.36502e-01 -8.18568e-02 -7.16163e+00  8.23195e+00 -1.71561e-02 -1.13749e+01
    3.75075e+00  7.25399e+00 -1.75325e+00 -2.68814e+00 -3.71128e+00 -4.62933e+00 -2.13747e+00 -1.89186e-01  1.29122e+00 -7.49380e-01  6.71712e-01
    -8.41923e-01  4.64997e+00  5.65808e-01 -3.08277e-01 -1.01687e+00  1.73127e-01 -8.92130e-01  1.89044e+00 -2.75543e-01 -7.72828e-01  5.36745e-01
    -3.65598e+00  7.56997e+00 -3.76373e+00 -1.74542e+00 -1.37540e-01 -5.55400e-01 -1.59195e-01  1.27910e-01  1.91906e+00  1.42119e+00 -4.35502e+00

    -1.70059e+00 -3.65695e+00  1.22367e+00 -5.74367e-01 -3.29571e+00  2.46316e+00  5.22353e+00  2.42038e+00  1.22919e+00 -9.22250e-01 -2.32028e+00


    0.00000e+00
    1.00000e+00

default.param: |
    NUMBER
    X_IMAGE
    Y_IMAGE
    ALPHA_J2000
    DELTA_J2000
    FLUX_APER
    FLUXERR_APER
    MAG_APER
    MAGERR_APER
    FLUX_AUTO
    FLUXERR_AUTO
    MAG_AUTO
    MAGERR_AUTO
    SNR_WIN
    THETA_IMAGE
    A_IMAGE
    B_IMAGE
    THETA_J2000
    A_WORLD
    B_WORLD
    # CLASS_STAR
    THRESHOLD
    BACKGROUND
    ISOAREA_IMAGE
    ISOAREAF_IMAGE
    KRON_RADIUS
    FLUX_RADIUS
    FLAGS

default.sex: |
    # Default configuration file for SExtractor 2.28.0
    # EB 2024-09-27
    #

    #-------------------------------- Catalog ------------------------------------

    CATALOG_NAME     test.cat       # name of the output catalog
    CATALOG_TYPE     ASCII_HEAD     # NONE,ASCII,ASCII_HEAD, ASCII_SKYCAT,
                                    # ASCII_VOTABLE, FITS_1.0 or FITS_LDAC
    PARAMETERS_NAME  default.param  # name of the file containing catalog contents

    #------------------------------- Extraction ----------------------------------

    DETECT_TYPE      CCD            # CCD (linear) or PHOTO (with gamma correction)
    DETECT_MINAREA   50              # min. # of pixels above threshold
    DETECT_MAXAREA   0              # max. # of pixels above threshold (0=unlimited)
    THRESH_TYPE      RELATIVE       # threshold type: RELATIVE (in sigmas)
                                    # or ABSOLUTE (in ADUs)s
    DETECT_THRESH    2             # <sigmas> or <threshold>,<ZP> in mag.arcsec-2
    ANALYSIS_THRESH  2              # <sigmas> or <threshold>,<ZP> in mag.arcsec-2

    FILTER           Y              # apply filter for detection (Y or N)?
    FILTER_NAME      default.conv   # name of the file containing the filter
    FILTER_THRESH                   # Threshold[s] for retina filtering

    DEBLEND_NTHRESH  2             # Number of deblending sub-thresholds
    DEBLEND_MINCONT  0.01        # Minimum contrast parameter for deblending

    CLEAN            Y              # Clean spurious detections? (Y or N)?
    CLEAN_PARAM      1.0            # Cleaning efficiency

    MASK_TYPE        CORRECT        # type of detection MASKing: can be one of
                                    # NONE, BLANK or CORRECT

    #-------------------------------- WEIGHTing ----------------------------------

    WEIGHT_TYPE      NONE            # type of WEIGHTing: NONE, BACKGROUND,
                                        # sMAP_RMS, MAP_VAR or MAP_WEIGHT
    RESCALE_WEIGHTS  Y               # Rescale input weights/variances (Y/N)?
    WEIGHT_IMAGE     weight.fits     # weight-map filename
    WEIGHT_GAIN      Y               # modulate gain (E/ADU) with weights? (Y/N)
    WEIGHT_THRESH                    # weight threshold[s] for bad pixels

    #-------------------------------- FLAGging -----------------------------------

    FLAG_IMAGE       flag.fits      # filename for an input FLAG-image
    FLAG_TYPE        OR             # flag pixel combination: OR, AND, MIN, MAX
                                    # or MOST

    #----------------------- Differential Geometry Map ---------------------------

    DGEO_TYPE        NONE           # Differential geometry map type: NONE or PIXEL
    DGEO_IMAGE       dgeo.fits      # Filename for input differential geometry image

    #------------------------------ Photometry -----------------------------------

    PHOT_APERTURES   9              # MAG_APER aperture diameter(s) in pixels
    PHOT_AUTOPARAMS  2.5, 3.5       # MAG_AUTO parameters: <Kron_fact>,<min_radius>
    PHOT_PETROPARAMS 2.0, 3.5       # MAG_PETRO parameters: <Petrosian_fact>,
                                    # <min_radius>
    PHOT_AUTOAPERS   0.0,0.0        # <estimation>,<measurement> minimum apertures
                                    # for MAG_AUTO and MAG_PETRO
    PHOT_FLUXFRAC    0.5            # flux fraction[s] used for FLUX_RADIUS

    SATUR_LEVEL      50000.0        # level (in ADUs) at which arises saturation
    SATUR_KEY        SATURATE       # keyword for saturation level (in ADUs)

    MAG_ZEROPOINT    0.0            # magnitude zero-point
    MAG_GAMMA        4.0            # gamma of emulsion (for photographic scans)
    GAIN             0.0            # detector gain in e-/ADU
    GAIN_KEY         GAIN           # keyword for detector gain in e-/ADU
    PIXEL_SCALE      0.04           # size of pixel in arcsec (0=use FITS WCS info)

    #------------------------- Star/Galaxy Separation ----------------------------

    SEEING_FWHM      1.2            # stellar FWHM in arcsec
    STARNNW_NAME     default.nnw    # Neural-Network_Weight table filename

    #------------------------------ Background -----------------------------------

    BACK_TYPE        AUTO           # AUTO or MANUAL
    BACK_VALUE       0.0            # Default background value in MANUAL mode
    BACK_PEARSON     2.5            # Pearson's factor alpha >= 1 with
                                    # (mode - mean) ~ alpha * (median - mean)
                                    # Legacy value is 2.5, but 3.5 is more accurate
    BACK_SIZE        31             # Background mesh: <size> or <width>,<height>
    BACK_FILTERSIZE  3              # Background filter: <size> or <width>,<height>

    BACKPHOTO_TYPE   LOCAL          # can be GLOBAL or LOCAL
    BACKPHOTO_THICK  24             # thickness of the background LOCAL annulus
    BACK_FILTTHRESH  0.0            # Threshold above which the background-
                                    # map filter operates

    #------------------------------ Check Image ----------------------------------

    CHECKIMAGE_TYPE  BACKGROUND,-BACKGROUND,SEGMENTATION          
                                    # can be NONE, BACKGROUND, BACKGROUND_RMS,
                                    # MINIBACKGROUND, MINIBACK_RMS, -BACKGROUND,
                                    # FILTERED, OBJECTS, -OBJECTS, SEGMENTATION,
                                    # or APERTURES
    CHECKIMAGE_NAME  background.fits,bkg_sub.fits,segmentation.fits     # Filename for the check-image

    #--------------------- Memory (change with caution!) -------------------------

    MEMORY_OBJSTACK  3000           # number of objects in stack
    MEMORY_PIXSTACK  500000         # number of pixels in stack
    MEMORY_BUFSIZE   1024           # number of lines in buffer

    #------------------------------- ASSOCiation ---------------------------------

    ASSOC_NAME       sky.list       # name of the ASCII file to ASSOCiate
    ASSOC_DATA       2,3,4          # columns of the data to replicate (0=all)
    ASSOC_PARAMS     2,3,4          # columns of xpos,ypos[,mag]
    ASSOCCOORD_TYPE  PIXEL          # ASSOC coordinates: PIXEL or WORLD
    ASSOC_RADIUS     2.0            # cross-matching radius (pixels)
    ASSOC_TYPE       NEAREST        # ASSOCiation method: FIRST, NEAREST, MEAN,
                                    # MAG_MEAN, SUM, MAG_SUM, MIN or MAX
    ASSOCSELEC_TYPE  MATCHED        # ASSOC selection type: ALL, MATCHED or -MATCHED

    #----------------------------- Miscellaneous ---------------------------------

    VERBOSE_TYPE     NORMAL         # can be QUIET, NORMAL or FULL
    HEADER_SUFFIX    .head          # Filename extension for additional headers
    WRITE_XML        N              # Write XML file (Y/N)?
    XML_NAME         sex.xml        # Filename for XML output
    XSL_URL          file:///usr/local/Cellar/sextractor/2.28.0/share/sextractor/sextractor.xsl
                                    # Filename for XSL style-sheet
    NTHREADS         1              # 1 single thread

    FITS_UNSIGNED    N              # Treat FITS integer values as unsigned (Y/N)?
    INTERP_MAXXLAG   16             # Max. lag along X for 0-weight interpolation
    INTERP_MAXYLAG   16             # Max. lag along Y for 0-weight interpolation
    INTERP_TYPE      ALL            # Interpolation type: NONE, VAR_ONLY or ALL

    #--------------------------- Experimental Stuff -----------------------------

    PSF_NAME         default.psf    # File containing the PSF model
    PSF_NMAX         1              # Max.number of PSFs fitted simultaneously
    PATTERN_TYPE     RINGS-HARMONIC # can RINGS-QUADPOLE, RINGS-OCTOPOLE,
                                    # RINGS-HARMONICS or GAUSS-LAGUERRE
    SOM_NAME         default.som    # File containing Self-Organizing Map weights